// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCn_15GwBx0Dl_GKSDnycnkHlgdS6sI8TE',
    appId: '1:728172766560:web:50817df4b7478b43f46a05',
    messagingSenderId: '728172766560',
    projectId: 'my-auth-project-c622a',
    authDomain: 'my-auth-project-c622a.firebaseapp.com',
    storageBucket: 'my-auth-project-c622a.firebasestorage.app',
    measurementId: 'G-RQ6E3E8960',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMcMxpgmSHcFAkO7oWX-RVHGNU7kUn0uo',
    appId: '1:728172766560:android:7762cb4ec0072b1df46a05',
    messagingSenderId: '728172766560',
    projectId: 'my-auth-project-c622a',
    storageBucket: 'my-auth-project-c622a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCH76VBN1KMhJQMh2X-Mfi97a1quHizV1Q',
    appId: '1:728172766560:ios:299f663916ea4e0af46a05',
    messagingSenderId: '728172766560',
    projectId: 'my-auth-project-c622a',
    storageBucket: 'my-auth-project-c622a.firebasestorage.app',
    iosBundleId: 'com.example.authProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCH76VBN1KMhJQMh2X-Mfi97a1quHizV1Q',
    appId: '1:728172766560:ios:299f663916ea4e0af46a05',
    messagingSenderId: '728172766560',
    projectId: 'my-auth-project-c622a',
    storageBucket: 'my-auth-project-c622a.firebasestorage.app',
    iosBundleId: 'com.example.authProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCn_15GwBx0Dl_GKSDnycnkHlgdS6sI8TE',
    appId: '1:728172766560:web:db317a60a0fb9b51f46a05',
    messagingSenderId: '728172766560',
    projectId: 'my-auth-project-c622a',
    authDomain: 'my-auth-project-c622a.firebaseapp.com',
    storageBucket: 'my-auth-project-c622a.firebasestorage.app',
    measurementId: 'G-6SFBQZKKNN',
  );
}